Update provider.go
aka-somix/virtual-kubelet pull request #2
Opened 2023-04-25 14:17 UTC by windyear

optimize: add PortForward to the Provider interface and add the PortForward from the provider to the PodHandlerConfig.

2023-04-27 15:17 UTC, aka-somix commented
Hi @windyear !
Thank you for the PR. I saw the conversation on the upstream pull request. You are totally correct we forgot to add this part. 
Since the PR will be managed directly upstream, I wil close this one for now.

If anything changes we will reopen it from here. 🚀

2023-04-30 18:12 UTC, aka-somix approved these changes
LGTM

2023-05-01 08:21 UTC, aka-somix commented
@windyear it looks like there is something missing. 
From the logs i see that the MockProvider is no longer implementing the Provider interface.  It should be because of the Portforward method is not implemented. 

Could you please also provide a fast mock implementation for it?

Thanks 🚀

2023-05-04 14:02 UTC, windyear commented
add fast mock implementation for mock provider with portforward](https://github.com/aka-somix/virtual-kubelet/pull/2/commits/a330865499c76ab80e01a3febfca1e32a9b64bbe). @aka-somix

2023-05-05 13:53 UTC, ssoBAekiL commented
@windyear some changes are not passing the linting requirements. Could you take a look at that?
As soon as all tests are successful we'll merge the PR.

Thanks!

2023-05-05 14:48 UTC, ssoBAekiL requested changes

2023-05-05 14:48 UTC, ssoBAekiL commented on node/nodeutil/provider.go
> +				PortForward:      p.PortForward,
Indentation allignment should fix the lint issue

2023-05-05 15:34 UTC, windyear commented on node/nodeutil/provider.go
> +				PortForward:      p.PortForward,
already fix, thanks for point out

2023-05-05 15:53 UTC, ssoBAekiL approved these changes

2023-05-16 06:50 UTC, merged